### PR TITLE
Rewrite api in Typescript

### PR DESCRIPTION
**Pull request by atomic-structure**
Hi all!
As promised I spent a few days rewriting the complete backend in Typescript.
I avoided breaking changes for the API endpoints to make this PR 'easier'.

Things I tested:

1. API is compiling in Typescript
2. All necessary tools/libs to build the API are mentioned in the package.json
3. Bash script to insert example data is working
4. Intensive testing of Person & Group API as I did some refactorings
5. Tested setup with docker-compose

### CODE REVIEW

**Comment by lkoehl** [comment]
Multiple things don't work anymore:

First of all I have problems with the example data script. My output is:
```
show student state
[]{"error":"Specified user id is not know to the system"}{"error":"Specified user id is not know to the system"}show group state
[{"name":"3B-Mathe","personIds":["19a6fde5-83fe-478b-8c09-2dc472f62b26","3522be1b-862f-4732-b04b-fe1033fcd533"],"id":"5e79deeda5b6b3143100181c"},{"name":"3B-Englisch","personIds":["3b2a52aa-c72c-4a12-bd0f-8be7a532cf18","0b487ee0-17c2-4eb5-8008-cdd2232a9760","441e9629-94e3-4be6-a6e0-d969537ccd84"],"id":"5e79deeda5b6b3143100181d"}]
```
Multiple PersonAlreadyExistingException and PersonNotFoundException gets thrown.

Using the website I can't save files anymore and the existing files are not shown correctly in the list.

Entering classes I get a 
```
[Error] Failed to load resource: the server responded with a status of 500 (Internal Server Error) (students, line 0)
```
and a 
```
Error: Argument passed in must be a single String of 12 bytes or a string of 24 hex characters
    at new ObjectID (/Users/lukaskohl/TeachAtHome/backend/node_modules/bson/lib/bson/objectid.js:59:11)
    at MongoDBService.getCollectionEntries (/Users/lukaskohl/TeachAtHome/backend/build/persistance/mongodb/MongoDBService.js:48:28)
    at PersonRepository.getPersonById (/Users/lukaskohl/TeachAtHome/backend/build/persons/PersonRepository.js:9:54)
    at PersonService.getPersonById (/Users/lukaskohl/TeachAtHome/backend/build/persons/PersonService.js:60:52)
    at GroupEndpoints.getStudentsByGroup (/Users/lukaskohl/TeachAtHome/backend/build/groups/GroupEndpoints.js:13:70)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error: Argument passed in must be a single String of 12 bytes or a string of 24 hex characters
    at new ObjectID (/Users/lukaskohl/TeachAtHome/backend/node_modules/bson/lib/bson/objectid.js:59:11)
    at MongoDBService.getCollectionEntries (/Users/lukaskohl/TeachAtHome/backend/build/persistance/mongodb/MongoDBService.js:48:28)
    at PersonRepository.getPersonById (/Users/lukaskohl/TeachAtHome/backend/build/persons/PersonRepository.js:9:54)
    at PersonService.getPersonById (/Users/lukaskohl/TeachAtHome/backend/build/persons/PersonService.js:60:52)
    at GroupEndpoints.getStudentsByGroup (/Users/lukaskohl/TeachAtHome/backend/build/groups/GroupEndpoints.js:13:70)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error: Argument passed in must be a single String of 12 bytes or a string of 24 hex characters
    at new ObjectID (/Users/lukaskohl/TeachAtHome/backend/node_modules/bson/lib/bson/objectid.js:59:11)
    at MongoDBService.getCollectionEntries (/Users/lukaskohl/TeachAtHome/backend/build/persistance/mongodb/MongoDBService.js:48:28)
    at PersonRepository.getPersonById (/Users/lukaskohl/TeachAtHome/backend/build/persons/PersonRepository.js:9:54)
    at PersonService.getPersonById (/Users/lukaskohl/TeachAtHome/backend/build/persons/PersonService.js:60:52)
    at GroupEndpoints.getStudentsByGroup (/Users/lukaskohl/TeachAtHome/backend/build/groups/GroupEndpoints.js:13:70)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by atomic-structure** [comment]
First of all:

Thank you very much for taking this so serious! :-)

> Multiple things don't work anymore:
> 
> First of all I have problems with the example data script. My output is:
> 
> ```
> show student state
> []{"error":"Specified user id is not know to the system"}{"error":"Specified user id is not know to the system"}show group state
> [{"name":"3B-Mathe","personIds":["19a6fde5-83fe-478b-8c09-2dc472f62b26","3522be1b-862f-4732-b04b-fe1033fcd533"],"id":"5e79deeda5b6b3143100181c"},{"name":"3B-Englisch","personIds":["3b2a52aa-c72c-4a12-bd0f-8be7a532cf18","0b487ee0-17c2-4eb5-8008-cdd2232a9760","441e9629-94e3-4be6-a6e0-d969537ccd84"],"id":"5e79deeda5b6b3143100181d"}]
> ```
> 
> Multiple PersonAlreadyExistingException and PersonNotFoundException gets thrown.

Did you clean your Mongo db before inserting the new data?
I fixed an issue related to the mongodb:
We have not been able to get an entry based on the always existing '_id' property.
Now this is possible and might be a breaking change to the existing database model.

> Using the website I can't save files anymore and the existing files are not shown correctly in the list.
> 
> Entering classes I get a
> 
> ```
> [Error] Failed to load resource: the server responded with a status of 500 (Internal Server Error) (students, line 0)
> ```
> 
> and an error from the server:
> 
> ```
> Error: Argument passed in must be a single String of 12 bytes or a string of 24 hex characters
>     at new ObjectID (/Users/lukaskohl/TeachAtHome/backend/node_modules/bson/lib/bson/objectid.js:59:11)
>     at MongoDBService.getCollectionEntries (/Users/lukaskohl/TeachAtHome/backend/build/persistance/mongodb/MongoDBService.js:48:28)
>     at PersonRepository.getPersonById (/Users/lukaskohl/TeachAtHome/backend/build/persons/PersonRepository.js:9:54)
>     at PersonService.getPersonById (/Users/lukaskohl/TeachAtHome/backend/build/persons/PersonService.js:60:52)
>     at GroupEndpoints.getStudentsByGroup (/Users/lukaskohl/TeachAtHome/backend/build/groups/GroupEndpoints.js:13:70)
>     at processTicksAndRejections (internal/process/task_queues.js:93:5)
> ```
> 
> Since there are multiple things wrong, is there any chance I made a mistake starting the backend server? I followed your updated readme

Maybe this is related to the mentioned question above.
Running the sample script on a fresh mongodb 'works on my machine' (I hate that sentence :-/)

**Comment by atomic-structure** [comment]
Already found at least one issue but I will test it more intensive especially in combination with the frontend.
I will update the PR by tomorrow evening.

**Comment by atomic-structure** [comment]
@lkoehl : Fixed document service + corrected collection name for document repository.
Tested Frontend, please rerun your tests and check if the PR is working now.

**Comment by lkoehl** [comment]
Looks better ;D, but I still get a problem with the students. They are not shown on the frontend. I tracked the error down to the shell script not adding them to the database. I don't know why this doesn't work. Master works fine for me.

**Pull request merged**
